export const trainers = [
  {
    TrainerId: "1",
    Name: "Amit",
    Email: "amit@example.com",
    Phone: "1234567890",
    Technology: "React",
    Skills: "React,Redux",
  },
  {
    TrainerId: "2",
    Name: "Nina",
    Email: "nina@example.com",
    Phone: "0987654321",
    Technology: "Angular",
    Skills: "Angular,RxJS",
  },
  {
    TrainerId: "3",
    Name: "Vamit",
    Email: "Vamit@example.com",
    Phone: "1234567890",
    Technology: "React",
    Skills: "React,Redux",
  },
  {
    TrainerId: "4",
    Name: "Rina",
    Email: "Rina@example.com",
    Phone: "0987654321",
    Technology: "Angular",
    Skills: "Angular,RxJS",
  },
  {
    TrainerId: "5",
    Name: "Soumit",
    Email: "Soumit@example.com",
    Phone: "1234567890",
    Technology: "React",
    Skills: "React,Redux",
  },
  {
    TrainerId: "6",
    Name: "LaNina",
    Email: "Lanina@example.com",
    Phone: "0987654321",
    Technology: "Angular",
    Skills: "Angular,RxJS",
  },
];
